### ISSUE TITLE
please publish/tag releases in github

### ISSUE THREAD

**Issue by sandrotosi** [AmatanHead/sphinx-a4doc#5]
Hello,
would it be possible to tag releases on github too? this would help us packages (debian in my case) to fetch all the files, that not necessarily end up in the PyPI tarball (f.e. doc/)

thanks!

**Comment by AmatanHead** [comment]
Hello @sandrotosi,

Sorry for delay, starting from 1.2.2 I will use tags for new releases. Thanks to @miurahr for helping with PyPI integration 😸

**Comment by miurahr** [comment]
@AmatanHead Do you want to automate creation of github release? I can do PR.
