### ISSUE TITLE
Unquoted litteral in auto grammar

### ISSUE THREAD

**Issue by sbenilan** [AmatanHead/sphinx-a4doc#8]
Hello,

First your sphinx plugging is lovely, I am using it to document a DSL I am working on. This DSL grammar is written with ANTLR4 g4 and I use autogrammar feature.

Would it be possible to add `:literal-rendering:` (including contents-unquoted) support to the `a4:autogrammar` directive ?

Thanks!

**Comment by AmatanHead** [comment]
Hi! Sorry for taking long to respond, was busy with my primary work. Yes, this feature is supported, you can override any diagram option from the `autogrammar` directive, you'll need to add `diagram-` prefix. In your case, that would be

```
.. a4:autogrammar:: Name
   :diagram-literal-rendering: contents-unquoted
```

See [docs] for more info.

[docs]: https://amatanhead.github.io/sphinx-a4doc/#option-a4-grammar-diagram
